### PR TITLE
Fly

### PR DESCRIPTION
**Pull request by jbaxleyiii**

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
```diff
  type User {
    id: ID!
+   added: [Friend]          ✅
-   changed: Return           
+   changed: ReturnNew       🚨
-   removed: String          🚨
  }
```

**Comment by stubailo** [comment]
```graphql
type User {
  id: ID!
  added: [Friend]          # ✅ Field added
  changed: ReturnNew # 🚨 Return type changed, used to be Return          
  removed: String         # 🚨 Field removed
}
```

**Comment by jbaxleyiii** [comment]
**Option 1**: Group by change code and sorted by change type with top locked iconography of change type
```graphql
type User {

  # Changes                🚨
  newthing: ReturnNew      # Return type changed, used to be Return
  thing: OtherThing        # Return type changed, used to be Thing

  # Removals               🚨
  removed: String          # Field removed

  # Additions              ✅
  added: [Friend]          # Field added
     
}
```

**Option 2**: Group by change code and sorted by change type with per change iconography

```graphql
type User {
  id: ID!

  # Field Return Type Changes
  changed: ReturnNew       # 🚨 Return type changed, used to be Return     
  thing: OtherThing        # 🚨 Return type changed, used to be Thing

  # Field Removal
  # removed: String          🚨 Field removed

  # Field Additions
  added: [Friend]          # ✅ Field added

}
```
**Option 3**: Group by change type and icongraphy noted at section level (drops change code)
```graphql
type User {

  # 🚨 Breaking 🚨
  newthing: ReturnNew      # Return type changed, used to be Return
  thing: OtherThing        # Return type changed, used to be Thing
  removed: String          # Field removed

  # ✅ Changes ✅
  added: [Friend]          # Field added
     
}
```
**Option 4**: Group by change type and icongraphy noted at section level and sub grouped by change type
```graphql
type User {

  """

    🚨 Breaking 🚨

  """
  # Field Return Type Changed
  newthing: ReturnNew      # Return type changed, used to be Return
  thing: OtherThing        # Return type changed, used to be Thing
  
   # Field Addition
  removed: String          # Field removed

  """

    ✅ Changes ✅

  """
  # Field Additions
  added: [Friend]          # Field added
     
}
```
**Option 5**: Group by change type and icongraphy noted at section level and sub grouped by change type
```graphql
type User {

  # 🚨 Breaking 🚨
  # Field Return Type Changed
  newthing: ReturnNew      # Return type changed, used to be Return
  thing: OtherThing        # Return type changed, used to be Thing
  
   # Field Addition
  removed: String          # Field removed

  # ✅ Changes ✅
  # Field Additions
  added: [Friend]          # Field added
     
}
```

**Comment by jbaxleyiii** [comment]
Other options:
```graphql
# ✅ OBJECT_IMPLEMENTS_NEW_TYPE: User now implements Node type
type User implements Node {

  """
  🚨 FIELD_TYPE_CHANGE: Return type used to be Foobar
  🚨 NON_NULL_ARG_ADDED: Argment of arg has return type of Int!
  ✅ NEW_ARG: Argument of second added
  """
  thing(arg: Int!, second: String): [Foo]

   # 🚨FIELD_TYPE_CHANGE: Return type changed, used to be Return
  changed: ReturnNew

}

**Comment by jbaxleyiii** [comment]
A more verbose version

```graphql
type User {

  # 🚨 Breaking 🚨
  newthing(arg: Int!, second: String): [Foo]
  thing: OtherThing
  removed: String

  # ✅ Changes ✅
  otherThing: [Friend]

}
```
<details>
🚨 Breaking 🚨

* FIELD_TYPE_CHANGE: Return type used to be Foobar
*  NON_NULL_ARG_ADDED: Argment of arg has return type of Int!

✅ Changes ✅

* FIELD_ADDED: Field otherThing added

**Comment by jbaxleyiii** [comment]
### Operation Change Details
```graphql
query GetUser($id: ID!) {
  user(id: $id) {

    # 🚨 Breaking 🚨
    gender

    # ⚡ Warning ⚡
    fullName

    # ✅ Safe ✅
    firstName
}
```
**Breaking**

* FIELD_NOT_FOUND: The field `user.gender`  does not exist on type `User`

**Warning**
* FIELD_DEPRECATED: Field `fullName` is deprecated on `User`

**Safe**

* FIELD_ADDED: Field `user.firstname` added

**Pull request closed without merging**
